upstream fastapi {
    server fastapi:8000;
}
upstream yii2 {
    server yii2:9000;
}
server {
    listen 80;
    server_name localhost;
    root /var/www/html/web;
    index index.php;
    access_log /var/log/nginx/access.log;
    error_log /dev/stderr notice;

    location /nginx_status {
        stub_status on;
        allow 172.0.0.0/8;
        deny all;
    }

    location /api/ {
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 300s;
        client_max_body_size 50m;
    }

    location /terminal/ {
        resolver 127.0.0.11 valid=10s;
        set $termix_upstream http://termix:8080;

        proxy_pass $termix_upstream/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_request_buffering off;

        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    location = / {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        alias /etc/nginx/static/;
        try_files index.html =404;
    }

    location /stand.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        alias /etc/nginx/static/stand.html;
    }

    location /test {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass yii2;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location ~ /\.(ht|git) {
        deny all;
    }

    
}
