apiVersion: 1
contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram-receiver
        type: telegram
        settings:
          bottoken: "$TELEGRAM_BOT_TOKEN"
          chatid: "720064035"
          message: |
            {{ range .Alerts }}
            {{ if eq .Status "firing" }}🔴{{ else }}🟢{{ end }} {{ .Labels.alertname }}
            📋 {{ .Annotations.summary }}
            🏷 Job: {{ .Labels.job }}
            📊 Instance: {{ .Labels.instance }}
            Статус: {{ .Status }}
            {{ end }}
